name: "CricManager App CI"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  setup:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DEVISE_JWT_SECRET_KEY: dummy_secret_for_ci
      DATABASE_URL: postgres://rails:password@localhost:5432/rails_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Run DB migrations (validate)
        run: bin/rails db:prepare

  test:
    needs: setup
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      RAILS_ENV: test
      DEVISE_JWT_SECRET_KEY: dummy_secret_for_ci
      DATABASE_URL: postgres://rails:password@localhost:5432/rails_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Set up database
        run: |
          cp config/database.yml.ci config/database.yml
          bin/rails db:schema:load

      - name: Run RSpec tests
        run: bundle exec rspec

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop --parallel

  # Optional: Add later when Brakeman & Bundler Audit are set up
  # security:
  #   if: always()
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 3.2.2
  #         bundler-cache: true

  #     - name: Install security tools
  #       run: |
  #         bundle binstubs brakeman bundler-audit
  #         bundle install

  #     - name: Run Bundler Audit
  #       run: bin/bundler-audit --update

  #     - name: Run Brakeman
  #       run: bin/brakeman -q -w2
